version: "3.1"
services:
  jenkins:
    build: .
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - "/home/gdyuldin/jenkins/jenkins_data:/var/jenkins_home"
    ports:
      - "8080:8080"
      - "50000:50000"

